version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - wordpress
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-u", "${DB_USER}", "--password=${DB_PASS}", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${SMTP_PORT}:8025
    networks:
      - wordpress

  wordpress:
    build:
      context: ./srv
      dockerfile: ./Dockerfile
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL=${GIT_EMAIL}
        - NODE_VERSION=${NODE_VERSION}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_HOST=${DB_HOST}
        - WP_LOCALE=${WP_LOCALE}
        - WP_VERSION=${WP_VERSION}
        - SITE_URL=${SITE_URL}
        - SITE_NAME=${SITE_NAME}
        - ADMIN_NAME=${ADMIN_NAME}
        - ADMIN_PASS=${ADMIN_PASS}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - SMTP_SERVER=${SMTP_SERVER}
        - SMTP_PORT=${PHP_SMTP_PORT}
        - PHP_EXECUTION_TIME=${PHP_EXECUTION_TIME}
        - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
    image: srv
    restart: always
    depends_on:
      - db
      - mailhog
    networks:
      - wordpress
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${DEBUG_PORT}:9003
    volumes:
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/uploads:/var/www/html/wp-content/uploads
      - ./srv/wordpress:/var/www/html
volumes:
  db_data:
networks:
  wordpress:
